// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxtJPRGq7q6vVlibrAQbNFRT3LbLd1dSg',
    appId: '1:529076727418:web:b5445c2be50b1f7b6bd5c3',
    messagingSenderId: '529076727418',
    projectId: 'test2-3554b',
    authDomain: 'test2-3554b.firebaseapp.com',
    storageBucket: 'test2-3554b.appspot.com',
    measurementId: 'G-1P8PVVW1Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPQ8N-QJMO1I-8uMlLpp39tZ9t7Y5G3YM',
    appId: '1:529076727418:android:e336a21856e19fde6bd5c3',
    messagingSenderId: '529076727418',
    projectId: 'test2-3554b',
    storageBucket: 'test2-3554b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR6Jfrw36QOkUH6KkikS797rDQxJdGdSY',
    appId: '1:529076727418:ios:c167d2498683e6906bd5c3',
    messagingSenderId: '529076727418',
    projectId: 'test2-3554b',
    storageBucket: 'test2-3554b.appspot.com',
    iosBundleId: 'com.example.foodDeliver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR6Jfrw36QOkUH6KkikS797rDQxJdGdSY',
    appId: '1:529076727418:ios:c167d2498683e6906bd5c3',
    messagingSenderId: '529076727418',
    projectId: 'test2-3554b',
    storageBucket: 'test2-3554b.appspot.com',
    iosBundleId: 'com.example.foodDeliver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxtJPRGq7q6vVlibrAQbNFRT3LbLd1dSg',
    appId: '1:529076727418:web:7af572f7de5af1146bd5c3',
    messagingSenderId: '529076727418',
    projectId: 'test2-3554b',
    authDomain: 'test2-3554b.firebaseapp.com',
    storageBucket: 'test2-3554b.appspot.com',
    measurementId: 'G-1NZYLWS8LP',
  );

}